/*
** This file was automatically generated by fdtrans.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/xadmaster.h>
#include <proto/xadmaster.h>

STATIC ULONG stub_OpenPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

        return (ULONG) Self->Open(0);
}
struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, stub_OpenPPC };

STATIC ULONG stub_ClosePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

        return (ULONG) Self->Close();
}
struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, stub_ClosePPC };

STATIC ULONG stub_ExpungePPC(ULONG *regarray)
{
        return 0UL;
}
struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray)
{
        return 0UL;
}
struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

#define IxadMaster Self

static xadPTR stub_xadAllocObjectAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadAllocObjectA(
                (xadUINT32)regarray[0],
                (const struct TagItem *)regarray[8]
        );
}
struct EmuTrap stub_xadAllocObjectA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadAllocObjectAPPC };

static void stub_xadFreeObjectAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        xadFreeObjectA(
                (xadPTR)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadFreeObjectA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadFreeObjectAPPC };

static struct xadClient * stub_xadRecogFileAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadRecogFileA(
                (xadSize)regarray[0],
                (const void *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadRecogFileA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadRecogFileAPPC };

static xadERROR stub_xadGetInfoAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetInfoA(
                (struct xadArchiveInfo *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadGetInfoA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetInfoAPPC };

static void stub_xadFreeInfoPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        xadFreeInfo(
                (struct xadArchiveInfo *)regarray[8]
        );
}
struct EmuTrap stub_xadFreeInfo = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadFreeInfoPPC };

static xadERROR stub_xadFileUnArcAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadFileUnArcA(
                (struct xadArchiveInfo *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadFileUnArcA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadFileUnArcAPPC };

static xadERROR stub_xadDiskUnArcAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadDiskUnArcA(
                (struct xadArchiveInfo *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadDiskUnArcA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadDiskUnArcAPPC };

static xadSTRPTR stub_xadGetErrorTextPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetErrorText(
                (xadERROR)regarray[0]
        );
}
struct EmuTrap stub_xadGetErrorText = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetErrorTextPPC };

static struct xadClient * stub_xadGetClientInfoPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetClientInfo(
        );
}
struct EmuTrap stub_xadGetClientInfo = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetClientInfoPPC };

static xadERROR stub_xadHookAccessPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadHookAccess(
                (xadUINT32)regarray[0],
                (xadSignSize)regarray[1],
                (xadPTR)regarray[8],
                (struct xadArchiveInfo *)regarray[9]
        );
}
struct EmuTrap stub_xadHookAccess = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadHookAccessPPC };

static xadERROR stub_xadConvertDatesAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadConvertDatesA(
                (const struct TagItem *)regarray[8]
        );
}
struct EmuTrap stub_xadConvertDatesA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadConvertDatesAPPC };

static xadUINT16 stub_xadCalcCRC16PPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadCalcCRC16(
                (xadUINT16)regarray[0],
                (xadUINT16)regarray[1],
                (xadSize)regarray[2],
                (const xadUINT8 *)regarray[8]
        );
}
struct EmuTrap stub_xadCalcCRC16 = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadCalcCRC16PPC };

static xadUINT32 stub_xadCalcCRC32PPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadCalcCRC32(
                (xadUINT32)regarray[0],
                (xadUINT32)regarray[1],
                (xadSize)regarray[2],
                (const xadUINT8 *)regarray[8]
        );
}
struct EmuTrap stub_xadCalcCRC32 = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadCalcCRC32PPC };

static xadPTR stub_xadAllocVecPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadAllocVec(
                (xadSize)regarray[0],
                (xadUINT32)regarray[1]
        );
}
struct EmuTrap stub_xadAllocVec = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadAllocVecPPC };

static void stub_xadCopyMemPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        xadCopyMem(
                (const void *)regarray[8],
                (xadPTR)regarray[9],
                (xadSize)regarray[0]
        );
}
struct EmuTrap stub_xadCopyMem = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadCopyMemPPC };

static xadERROR stub_xadHookTagAccessAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadHookTagAccessA(
                (xadUINT32)regarray[0],
                (xadSignSize)regarray[1],
                (xadPTR)regarray[8],
                (struct xadArchiveInfo *)regarray[9],
                (const struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_xadHookTagAccessA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadHookTagAccessAPPC };

static xadERROR stub_xadConvertProtectionAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadConvertProtectionA(
                (const struct TagItem *)regarray[8]
        );
}
struct EmuTrap stub_xadConvertProtectionA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadConvertProtectionAPPC };

static xadERROR stub_xadGetDiskInfoAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetDiskInfoA(
                (struct xadArchiveInfo *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadGetDiskInfoA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetDiskInfoAPPC };

static xadERROR stub_xadDiskFileUnArcAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadDiskFileUnArcA(
                (struct xadArchiveInfo *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadDiskFileUnArcA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadDiskFileUnArcAPPC };

static xadERROR stub_xadGetHookAccessAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetHookAccessA(
                (struct xadArchiveInfo *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadGetHookAccessA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetHookAccessAPPC };

static void stub_xadFreeHookAccessAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        xadFreeHookAccessA(
                (struct xadArchiveInfo *)regarray[8],
                (const struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_xadFreeHookAccessA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadFreeHookAccessAPPC };

static xadERROR stub_xadAddFileEntryAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadAddFileEntryA(
                (struct xadFileInfo *)regarray[8],
                (struct xadArchiveInfo *)regarray[9],
                (const struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_xadAddFileEntryA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadAddFileEntryAPPC };

static xadERROR stub_xadAddDiskEntryAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadAddDiskEntryA(
                (struct xadDiskInfo *)regarray[8],
                (struct xadArchiveInfo *)regarray[9],
                (const struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_xadAddDiskEntryA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadAddDiskEntryAPPC };

static xadERROR stub_xadGetFilenameAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetFilenameA(
                (xadUINT32)regarray[0],
                (xadSTRPTR)regarray[8],
                (const xadSTRING *)regarray[9],
                (const xadSTRING *)regarray[10],
                (const struct TagItem *)regarray[11]
        );
}
struct EmuTrap stub_xadGetFilenameA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetFilenameAPPC };

static xadSTRPTR stub_xadConvertNameAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadConvertNameA(
                (xadUINT32)regarray[0],
                (const struct TagItem *)regarray[8]
        );
}
struct EmuTrap stub_xadConvertNameA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadConvertNameAPPC };

static xadSTRPTR stub_xadGetDefaultNameAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetDefaultNameA(
                (const struct TagItem *)regarray[8]
        );
}
struct EmuTrap stub_xadGetDefaultNameA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetDefaultNameAPPC };

static const struct xadSystemInfo * stub_xadGetSystemInfoPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct xadMasterIFace *Self = (struct xadMasterIFace *) ExtLib->MainIFace;

        return xadGetSystemInfo(
        );
}
struct EmuTrap stub_xadGetSystemInfo = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_xadGetSystemInfoPPC };

ULONG VecTable68K[] = {
        (ULONG)&stub_Open,
        (ULONG)&stub_Close,
        (ULONG)&stub_Expunge,
        (ULONG)&stub_Reserved,
        (ULONG)&stub_xadAllocObjectA,
        (ULONG)&stub_xadFreeObjectA,
        (ULONG)&stub_xadRecogFileA,
        (ULONG)&stub_xadGetInfoA,
        (ULONG)&stub_xadFreeInfo,
        (ULONG)&stub_xadFileUnArcA,
        (ULONG)&stub_xadDiskUnArcA,
        (ULONG)&stub_xadGetErrorText,
        (ULONG)&stub_xadGetClientInfo,
        (ULONG)&stub_xadHookAccess,
        (ULONG)&stub_xadConvertDatesA,
        (ULONG)&stub_xadCalcCRC16,
        (ULONG)&stub_xadCalcCRC32,
        (ULONG)&stub_xadAllocVec,
        (ULONG)&stub_xadCopyMem,
        (ULONG)&stub_xadHookTagAccessA,
        (ULONG)&stub_xadConvertProtectionA,
        (ULONG)&stub_xadGetDiskInfoA,
        (ULONG)&stub_xadDiskFileUnArcA,
        (ULONG)&stub_xadGetHookAccessA,
        (ULONG)&stub_xadFreeHookAccessA,
        (ULONG)&stub_xadAddFileEntryA,
        (ULONG)&stub_xadAddDiskEntryA,
        (ULONG)&stub_xadGetFilenameA,
        (ULONG)&stub_xadConvertNameA,
        (ULONG)&stub_xadGetDefaultNameA,
        (ULONG)&stub_xadGetSystemInfo,
        (ULONG)-1
};
